### ISSUE TITLE
ValueError: (InvalidArgument) Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE (at /paddle/paddle/fluid/pybind/imperative.cc:221)

### ISSUE THREAD

**Issue by Labstrakt** [PaddlePaddle/Research#144]
I recently upgraded to `paddlepaddle-gpu 2.0.1.post110`, and this is the error I receive when running `./scripts/predict_graphsum_local_multinews.sh`:

```
Traceback (most recent call last):
  File "./src/run.py", line 35, in <module>
    run_graphsum(args)
  File "/home/matt/mr/algos/Research/NLP/ACL2020-GraphSum/src/networks/graphsum/run_graphsum.py", line 180, in main
    test_pyreader, test_graph_vars = graphsum.create_model(
  File "/home/matt/mr/algos/Research/NLP/ACL2020-GraphSum/src/networks/graphsum/graphsum_model.py", line 414, in create_model
    return self.fast_decode(pyreader_name)
  File "/home/matt/mr/algos/Research/NLP/ACL2020-GraphSum/src/networks/graphsum/graphsum_model.py", line 486, in fast_decode
    pyreader = fluid.layers.py_reader(
  File "/home/matt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layers/io.py", line 723, in py_reader
    return _py_reader(
  File "/home/matt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layers/io.py", line 444, in _py_reader
    startup_blk.append_op(
  File "/home/matt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3010, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/matt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
ValueError: (InvalidArgument) Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE (at /paddle/paddle/fluid/pybind/imperative.cc:221)
```

Python 3.8.8

```
Package          Version
---------------- -------------------
astor            0.8.1
certifi          2020.12.5
chardet          4.0.0
decorator        4.4.2
gast             0.4.0
idna             2.10
numpy            1.20.1
paddlepaddle-gpu 2.0.1.post110
Pillow           8.1.2
pip              21.0.1
protobuf         3.15.6
pyrouge          0.1.3
requests         2.25.1
sentencepiece    0.1.95
setuptools       52.0.0.post20210125
six              1.15.0
urllib3          1.26.4
wheel            0.36.2
```

**Comment by otakusbear** [comment]
I‘m facing the same problem, and I use paddle.enable_static() on the front of code to fix this problem. but unfortunately next problem has coming, concat op between new_step_id and alive_seq error, and after I reshape this tensor, I got another error about   nccl, I don't know if it's because I use single gpu to train the model.
