### ISSUE TITLE
DuEL_Baseline 在运行predict.sh的时候，报 var read_file_0.tmp_3 not in this block 错误

### ISSUE THREAD

**Issue by gjwei** [PaddlePaddle/Research#55]
详情log如下：
请问是哪里出错了吗，训练是没有问题的

环境：Cuda10+cudnn 7.4 + paddle1.7.1

> Traceback (most recent call last):
  File "./ernie/infer_type_ranker.py", line 358, in <module>
    main(args)
  File "./ernie/infer_type_ranker.py", line 163, in main
    main_program=predict_prog,
  File "/home/hadoop-aipnlp/cephfs/data/gaojianwei/research/ccks2020/DuEL_Baseline/env2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1221, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/hadoop-aipnlp/cephfs/data/gaojianwei/research/ccks2020/DuEL_Baseline/env2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1031, in prepend_feed_ops
    out = global_block.var(name)
  File "/home/hadoop-aipnlp/cephfs/data/gaojianwei/research/ccks2020/DuEL_Baseline/env2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2280, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var read_file_0.tmp_3 not in this block

**Comment by gjwei** [comment]
将paddle版本修改为1.5.2就可以了，已解决
