### ISSUE TITLE
PLATO fine-tuning raises error.. Please help!

### ISSUE THREAD

**Issue by rokslej** [PaddlePaddle/Research#91]
Hello,
I installed all requirements by using pip install -r requirement.txt
my cuda version, cudnn version are fit for paddlepaddle-gpu == 1.6.1.post107 (which is on your requirements.txt)
However, I met this error when I try to fine-tune the pre-trained model.

Traceback (most recent call last):
  File "./run.py", line 23, in <module>
    import paddle.fluid as fluid
  File "/home/joy/Research/NLP/Dialogue-PLATO/vplato/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/joy/Research/NLP/Dialogue-PLATO/vplato/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/joy/Research/NLP/Dialogue-PLATO/vplato/lib/python3.6/site-packages/paddle/fluid/core.py", line 187, in <module>
    raise e
  File "/home/joy/Research/NLP/Dialogue-PLATO/vplato/lib/python3.6/site-packages/paddle/fluid/core.py", line 167, in <module>
    from .core_avx import *
ImportError: /home/joy/Research/NLP/Dialogue-PLATO/vplato/lib/python3.6/site-packages/paddle/fluid/../libs/libmklml_intel.so: symbol __kmpc_omp_task_with_deps, version VERSION not defined in file libiomp5.so with link time reference
+ [[ false = true ]]

I tried my best to fix it, but it didn't work. What is the solution for this problem?

**Comment by rokslej** [comment]
I'm sorry,, I made a huge mistake...  I didn't install nccl! 
Thank you very much for sharing this implementation!! :)
