### ISSUE TITLE
RuntimeError: parallel_for failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Labstrakt** [PaddlePaddle/Research#99]
GrahpSum is very intriguing, but I'm unable to test with `./scripts/predict_graphsum_local_multinews.sh`.

The `log/lanch.log` file shows this error: `RuntimeError: parallel_for failed: no kernel image is available for execution on the device`

```(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ ./scripts/predict_graphsum_local_multinews.sh
+ source ./env_local/env_local.sh
++ set -xe
+++ hostname -i
++ export iplist=127.0.1.1
++ iplist=127.0.1.1
++ unset http_proxy
++ unset https_proxy
+ source ./env_local/utils.sh
++ set -u
+ source ./model_config/graphsum_model_conf_local_multinews
++ task=GraphSum_MDS
++ VOCAB_PATH=./vocab/spm9998_3.model
++ CONFIG_PATH=./model_config/graphsum_config.json
++ TASK_DATA_PATH=/home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle
++ lr_scheduler=noam_decay
++ use_fp16=False
++ use_fuse=True
++ use_hierarchical_allreduce=True
++ nccl_comm_num=3
++ loss_scaling=12800
++ WARMUP_PROP=0.01
++ WARMUP_STEPS=8000
++ beta1=0.9
++ beta2=0.998
++ eps=1e-9
++ LR_RATE=2.0
++ WEIGHT_DECAY=0.01
+ export FLAGS_eager_delete_tensor_gb=1.0
+ FLAGS_eager_delete_tensor_gb=1.0
+ export FLAGS_sync_nccl_allreduce=1
+ FLAGS_sync_nccl_allreduce=1
+ export FLAGS_fraction_of_gpu_memory_to_use=0.98
+ FLAGS_fraction_of_gpu_memory_to_use=0.98
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python -u ./src/run.py --model_name graphsum --use_cuda true --is_distributed false --use_multi_gpu_test False --use_fast_executor true --use_fp16 False --use_dynamic_loss_scaling False --init_loss_scaling 12800 --weight_sharing true --do_train false --do_val false --do_test true --do_dec true --verbose true --batch_size 30000 --in_tokens true --stream_job '' --init_pretraining_params '' --train_set /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/train --dev_set /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/valid --test_set /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/test --vocab_path ./vocab/spm9998_3.model --config_path model_config/graphsum_config.json --checkpoints ./models/graphsum_multinews --init_checkpoint ./models/graphsum_multinews/step_42976 --decode_path ./results/graphsum_multinews --lr_scheduler noam_decay --save_steps 10000 --weight_decay 0.01 --warmup_steps 8000 --validation_steps 20000 --epoch 100 --max_para_num 30 --max_para_len 60 --max_tgt_len 300 --max_out_len 300 --min_out_len 200 --beam_size 5 --graph_type similarity --len_penalty 0.6 --block_trigram True --report_rouge True --learning_rate 2.0 --skip_steps 100 --grad_norm 2.0 --pos_win 2.0 --label_smooth_eps 0.1 --num_iteration_per_drop_scope 10 --log_file log/graphsum_multinews_test.log --random_seed 1

(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ cat log/lanch.log
-----------  Configuration Arguments -----------
batch_size: 30000
beam_size: 5
beta1: 0.9
beta2: 0.998
block_trigram: True
checkpoints: ./models/graphsum_multinews
config_path: model_config/graphsum_config.json
decode_path: ./results/graphsum_multinews
decr_every_n_nan_or_inf: 2
decr_ratio: 0.8
dev_set: /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/valid
do_dec: True
do_lower_case: True
do_test: True
do_train: False
do_val: False
encoder_json_file: roberta_config/encoder.json
epoch: 100
eps: 1e-09
ernie_config_path: ernie_config/ernie_config.json
ernie_vocab_file: ernie_config/vocab.txt
evaluate_blue: False
grad_norm: 2.0
graph_type: similarity
in_tokens: True
incr_every_n_steps: 100
incr_ratio: 2.0
init_checkpoint: ./models/graphsum_multinews/step_42976
init_loss_scaling: 12800.0
init_pretraining_params:
is_distributed: False
label_smooth_eps: 0.1
learning_rate: 2.0
len_penalty: 0.6
log_file: log/graphsum_multinews_test.log
lr_scheduler: noam_decay
max_out_len: 300
max_para_len: 60
max_para_num: 30
max_seq_len: 512
max_tgt_len: 300
metrics: True
min_out_len: 200
model_name: graphsum
num_iteration_per_drop_scope: 10
pos_win: 2.0
random_seed: 1
report_rouge: True
roberta_config_path: roberta_config/roberta_config.json
roberta_vocab_file: roberta_config/vocab.txt
save_steps: 10000
skip_steps: 100
stream_job:
test_set: /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/test
train_set: /home/matt/mr/algos/GraphSum/data/MultiNews_data_tfidf_30_paddle/train
use_cuda: True
use_dynamic_loss_scaling: False
use_fast_executor: True
use_fp16: False
use_interval: False
use_multi_gpu_test: False
validation_steps: 20000
verbose: True
vocab_bpe_file: roberta_config/vocab.bpe
vocab_path: ./vocab/spm9998_3.model
warmup_proportion: 0.1
warmup_steps: 8000
weight_decay: 0.01
weight_sharing: True
------------------------------------------------
attention_probs_dropout_prob: 0.1
dec_graph_layers: 8
dec_word_pos_embedding_name: dec_word_pos_embedding
enc_graph_layers: 2
enc_sen_pos_embedding_name: enc_sen_pos_embedding
enc_word_layers: 6
enc_word_pos_embedding_name: enc_word_pos_embedding
hidden_act: relu
hidden_dropout_prob: 0.1
hidden_size: 256
initializer_range: 0.02
max_position_embeddings: 512
num_attention_heads: 8
postprocess_command: da
preprocess_command: n
word_embedding_name: word_embedding
------------------------------------------------
[2020-10-23 10:20:10,392 INFO] {'BOS': 4, 'EOS': 5, 'PAD': 6, 'EOT': 3, 'EOP': 7, 'EOQ': 8, 'UNK': 0}
[2020-10-23 10:20:10,393 WARNING] paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[2020-10-23 10:20:11,079 INFO] args.is_distributed: False
W1023 10:20:11.511365 3292334 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.1, Runtime API Version: 10.0
W1023 10:20:11.512548 3292334 device_context.cc:244] device: 0, cuDNN Version: 8.0.
W1023 10:20:11.862699 3292334 operator.cc:179] truncated_gaussian_random raises an exception thrust::system::system_error, parallel_for failed: no kernel image is available for execution on the device
/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./src/run.py", line 35, in <module>
    run_graphsum(args)
  File "/home/matt/mr/algos/Research/NLP/ACL2020-GraphSum/src/networks/graphsum/run_graphsum.py", line 219, in main
    exe.run(startup_prog)
  File "/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/matt/anaconda3/envs/graphsum/lib/python3.6/site-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
RuntimeError: parallel_for failed: no kernel image is available for execution on the device

(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ nvidia-smi
Fri Oct 23 10:21:38 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:21:00.0 Off |                  N/A |
| 30%   32C    P0    62W / 350W |      0MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ python -V
Python 3.6.9 :: Anaconda, Inc.
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep nltk
nltk             3.4.5
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep numpy
numpy            1.18.1
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep paddlepaddle
paddlepaddle-gpu 1.6.3.post107
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep pyrouge
pyrouge          0.1.3
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep regex
regex            2020.2.20
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep requests
requests         2.22.0
(graphsum) matt@DeepWhite:~/mr/algos/GraphSum $ pip list | grep sentencepiece
sentencepiece    0.1.85

(graphsum) matt@DeepWhite:~/mr/algos/GraphSum/log $ cat graphsum_multinews_test.log
[2020-10-23 10:16:45,647 INFO] {'BOS': 4, 'EOS': 5, 'PAD': 6, 'EOT': 3, 'EOP': 7, 'EOQ': 8, 'UNK': 0}
[2020-10-23 10:16:45,647 WARNING] paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[2020-10-23 10:16:46,320 INFO] args.is_distributed: False
[2020-10-23 10:19:38,037 INFO] {'BOS': 4, 'EOS': 5, 'PAD': 6, 'EOT': 3, 'EOP': 7, 'EOQ': 8, 'UNK': 0}
[2020-10-23 10:19:38,037 WARNING] paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[2020-10-23 10:19:38,740 INFO] args.is_distributed: False
[2020-10-23 10:20:10,392 INFO] {'BOS': 4, 'EOS': 5, 'PAD': 6, 'EOT': 3, 'EOP': 7, 'EOQ': 8, 'UNK': 0}
[2020-10-23 10:20:10,393 WARNING] paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[2020-10-23 10:20:11,079 INFO] args.is_distributed: False
[2020-10-23 10:43:43,574 INFO] {'BOS': 4, 'EOS': 5, 'PAD': 6, 'EOT': 3, 'EOP': 7, 'EOQ': 8, 'UNK': 0}
[2020-10-23 10:43:43,574 WARNING] paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[2020-10-23 10:43:44,258 INFO] args.is_distributed: False
```

**Comment by Labstrakt** [comment]
Ah, never mind! Upgrading to `paddlepaddle-gpu 1.8.5.post107` seems to have solved the issue.
